# Generated by Django 4.2.7 on 2023-12-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_bio_userprofile_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='media/images/profile_pics'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
