# Generated by Django 4.2.7 on 2023-12-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_bio_alter_userprofile_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='images/profile_pics'),
        ),
    ]
