# Generated by Django 4.2.7 on 2023-12-20 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchhistory',
            old_name='user_id',
            new_name='user',
        ),
    ]
