# Generated by Django 4.2.7 on 2023-12-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_alter_searchhistory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
