# Generated by Django 4.2.7 on 2024-01-10 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0010_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='feedback_media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpeg', 'jpg', 'gif', 'mov', 'mp4', 'mp3', 'mkv'])], verbose_name='Upload an image or video(recommended)'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='content',
            field=models.TextField(max_length=2500, verbose_name='Tell us more'),
        ),
    ]
