# Generated by Django 4.2.7 on 2024-01-13 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0013_alter_story_options_alter_post_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ads',
        ),
    ]
