# Generated by Django 4.2.7 on 2024-01-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0016_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=180),
        ),
    ]
